/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ServiceCentreRouteImport } from './routes/service-centre'
import { Route as TechnicianRouteImport } from './routes/technician'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTechniciansRouteImport } from './routes/admin/technicians'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as FarmerIndexRouteImport } from './routes/farmer/index'
import { Route as FarmerReportBreakdownRouteImport } from './routes/farmer/report-breakdown'
import { Route as RegisterFarmerRouteImport } from './routes/register/farmer'
import { Route as RegisterTechnicianRouteImport } from './routes/register/technician'
import { Route as TechnicianIndexRouteImport } from './routes/technician/index'
import { Route as TechnicianPendingRouteImport } from './routes/technician/pending'
import { Route as AdminRepairIdRouteImport } from './routes/admin/repair/$id'
import { Route as FarmerEquipmentIndexRouteImport } from './routes/farmer/equipment/index'
import { Route as FarmerEquipmentIdRouteImport } from './routes/farmer/equipment/$id'
import { Route as FarmerRepairIdRouteImport } from './routes/farmer/repair/$id'
import { Route as TechnicianJobIdRouteImport } from './routes/technician/job/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCentreRoute = ServiceCentreRouteImport.update({
  id: '/service-centre',
  path: '/service-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianRoute = TechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTechniciansRoute = AdminTechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => AdminRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerReportBreakdownRoute = FarmerReportBreakdownRouteImport.update({
  id: '/report-breakdown',
  path: '/report-breakdown',
  getParentRoute: () => FarmerRoute,
} as any)
const RegisterFarmerRoute = RegisterFarmerRouteImport.update({
  id: '/register/farmer',
  path: '/register/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTechnicianRoute = RegisterTechnicianRouteImport.update({
  id: '/register/technician',
  path: '/register/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianIndexRoute = TechnicianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechnicianRoute,
} as any)
const TechnicianPendingRoute = TechnicianPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => TechnicianRoute,
} as any)
const AdminRepairIdRoute = AdminRepairIdRouteImport.update({
  id: '/repair/$id',
  path: '/repair/$id',
  getParentRoute: () => AdminRoute,
} as any)
const FarmerEquipmentIndexRoute = FarmerEquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerEquipmentIdRoute = FarmerEquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerRepairIdRoute = FarmerRepairIdRouteImport.update({
  id: '/repair/$id',
  path: '/repair/$id',
  getParentRoute: () => FarmerRoute,
} as any)
const TechnicianJobIdRoute = TechnicianJobIdRouteImport.update({
  id: '/job/$id',
  path: '/job/$id',
  getParentRoute: () => TechnicianRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/service-centre': typeof ServiceCentreRoute
  '/technician': typeof TechnicianRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/farmer/report-breakdown': typeof FarmerReportBreakdownRoute
  '/register/farmer': typeof RegisterFarmerRoute
  '/register/technician': typeof RegisterTechnicianRoute
  '/technician/pending': typeof TechnicianPendingRoute
  '/admin/': typeof AdminIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/admin/repair/$id': typeof AdminRepairIdRoute
  '/farmer/equipment/$id': typeof FarmerEquipmentIdRoute
  '/farmer/repair/$id': typeof FarmerRepairIdRoute
  '/technician/job/$id': typeof TechnicianJobIdRoute
  '/farmer/equipment/': typeof FarmerEquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/service-centre': typeof ServiceCentreRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/farmer/report-breakdown': typeof FarmerReportBreakdownRoute
  '/register/farmer': typeof RegisterFarmerRoute
  '/register/technician': typeof RegisterTechnicianRoute
  '/technician/pending': typeof TechnicianPendingRoute
  '/admin': typeof AdminIndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/technician': typeof TechnicianIndexRoute
  '/admin/repair/$id': typeof AdminRepairIdRoute
  '/farmer/equipment/$id': typeof FarmerEquipmentIdRoute
  '/farmer/repair/$id': typeof FarmerRepairIdRoute
  '/technician/job/$id': typeof TechnicianJobIdRoute
  '/farmer/equipment': typeof FarmerEquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/service-centre': typeof ServiceCentreRoute
  '/technician': typeof TechnicianRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/farmer/report-breakdown': typeof FarmerReportBreakdownRoute
  '/register/farmer': typeof RegisterFarmerRoute
  '/register/technician': typeof RegisterTechnicianRoute
  '/technician/pending': typeof TechnicianPendingRoute
  '/admin/': typeof AdminIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/admin/repair/$id': typeof AdminRepairIdRoute
  '/farmer/equipment/$id': typeof FarmerEquipmentIdRoute
  '/farmer/repair/$id': typeof FarmerRepairIdRoute
  '/technician/job/$id': typeof TechnicianJobIdRoute
  '/farmer/equipment/': typeof FarmerEquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/farmer'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/profile'
    | '/service-centre'
    | '/technician'
    | '/.well-known/oauth-protected-resource'
    | '/admin/technicians'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/farmer/report-breakdown'
    | '/register/farmer'
    | '/register/technician'
    | '/technician/pending'
    | '/admin/'
    | '/farmer/'
    | '/technician/'
    | '/admin/repair/$id'
    | '/farmer/equipment/$id'
    | '/farmer/repair/$id'
    | '/technician/job/$id'
    | '/farmer/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/profile'
    | '/service-centre'
    | '/.well-known/oauth-protected-resource'
    | '/admin/technicians'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/farmer/report-breakdown'
    | '/register/farmer'
    | '/register/technician'
    | '/technician/pending'
    | '/admin'
    | '/farmer'
    | '/technician'
    | '/admin/repair/$id'
    | '/farmer/equipment/$id'
    | '/farmer/repair/$id'
    | '/technician/job/$id'
    | '/farmer/equipment'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/farmer'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/profile'
    | '/service-centre'
    | '/technician'
    | '/.well-known/oauth-protected-resource'
    | '/admin/technicians'
    | '/auth/confirm'
    | '/auth/reset-password'
    | '/farmer/report-breakdown'
    | '/register/farmer'
    | '/register/technician'
    | '/technician/pending'
    | '/admin/'
    | '/farmer/'
    | '/technician/'
    | '/admin/repair/$id'
    | '/farmer/equipment/$id'
    | '/farmer/repair/$id'
    | '/technician/job/$id'
    | '/farmer/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FarmerRoute: typeof FarmerRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ProfileRoute: typeof ProfileRoute
  ServiceCentreRoute: typeof ServiceCentreRoute
  TechnicianRoute: typeof TechnicianRouteWithChildren
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  RegisterFarmerRoute: typeof RegisterFarmerRoute
  RegisterTechnicianRoute: typeof RegisterTechnicianRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-centre': {
      id: '/service-centre'
      path: '/service-centre'
      fullPath: '/service-centre'
      preLoaderRoute: typeof ServiceCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician': {
      id: '/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof TechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/technicians': {
      id: '/admin/technicians'
      path: '/technicians'
      fullPath: '/admin/technicians'
      preLoaderRoute: typeof AdminTechniciansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/report-breakdown': {
      id: '/farmer/report-breakdown'
      path: '/report-breakdown'
      fullPath: '/farmer/report-breakdown'
      preLoaderRoute: typeof FarmerReportBreakdownRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/register/farmer': {
      id: '/register/farmer'
      path: '/register/farmer'
      fullPath: '/register/farmer'
      preLoaderRoute: typeof RegisterFarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/technician': {
      id: '/register/technician'
      path: '/register/technician'
      fullPath: '/register/technician'
      preLoaderRoute: typeof RegisterTechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/': {
      id: '/technician/'
      path: '/'
      fullPath: '/technician/'
      preLoaderRoute: typeof TechnicianIndexRouteImport
      parentRoute: typeof TechnicianRoute
    }
    '/technician/pending': {
      id: '/technician/pending'
      path: '/pending'
      fullPath: '/technician/pending'
      preLoaderRoute: typeof TechnicianPendingRouteImport
      parentRoute: typeof TechnicianRoute
    }
    '/admin/repair/$id': {
      id: '/admin/repair/$id'
      path: '/repair/$id'
      fullPath: '/admin/repair/$id'
      preLoaderRoute: typeof AdminRepairIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/farmer/equipment/': {
      id: '/farmer/equipment/'
      path: '/equipment'
      fullPath: '/farmer/equipment/'
      preLoaderRoute: typeof FarmerEquipmentIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/equipment/$id': {
      id: '/farmer/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/farmer/equipment/$id'
      preLoaderRoute: typeof FarmerEquipmentIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/repair/$id': {
      id: '/farmer/repair/$id'
      path: '/repair/$id'
      fullPath: '/farmer/repair/$id'
      preLoaderRoute: typeof FarmerRepairIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/technician/job/$id': {
      id: '/technician/job/$id'
      path: '/job/$id'
      fullPath: '/technician/job/$id'
      preLoaderRoute: typeof TechnicianJobIdRouteImport
      parentRoute: typeof TechnicianRoute
    }
  }
}

interface AdminRouteChildren {
  AdminTechniciansRoute: typeof AdminTechniciansRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRepairIdRoute: typeof AdminRepairIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTechniciansRoute: AdminTechniciansRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRepairIdRoute: AdminRepairIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FarmerRouteChildren {
  FarmerReportBreakdownRoute: typeof FarmerReportBreakdownRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  FarmerEquipmentIdRoute: typeof FarmerEquipmentIdRoute
  FarmerRepairIdRoute: typeof FarmerRepairIdRoute
  FarmerEquipmentIndexRoute: typeof FarmerEquipmentIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerReportBreakdownRoute: FarmerReportBreakdownRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  FarmerEquipmentIdRoute: FarmerEquipmentIdRoute,
  FarmerRepairIdRoute: FarmerRepairIdRoute,
  FarmerEquipmentIndexRoute: FarmerEquipmentIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

interface TechnicianRouteChildren {
  TechnicianPendingRoute: typeof TechnicianPendingRoute
  TechnicianIndexRoute: typeof TechnicianIndexRoute
  TechnicianJobIdRoute: typeof TechnicianJobIdRoute
}

const TechnicianRouteChildren: TechnicianRouteChildren = {
  TechnicianPendingRoute: TechnicianPendingRoute,
  TechnicianIndexRoute: TechnicianIndexRoute,
  TechnicianJobIdRoute: TechnicianJobIdRoute,
}

const TechnicianRouteWithChildren = TechnicianRoute._addFileChildren(
  TechnicianRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FarmerRoute: FarmerRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ProfileRoute: ProfileRoute,
  ServiceCentreRoute: ServiceCentreRoute,
  TechnicianRoute: TechnicianRouteWithChildren,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  RegisterFarmerRoute: RegisterFarmerRoute,
  RegisterTechnicianRoute: RegisterTechnicianRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
