/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TechnicianRouteImport } from './routes/technician'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as FarmerIndexRouteImport } from './routes/farmer/index'
import { Route as FarmerReportBreakdownRouteImport } from './routes/farmer/report-breakdown'
import { Route as TechnicianIndexRouteImport } from './routes/technician/index'
import { Route as AdminRepairIdRouteImport } from './routes/admin/repair/$id'
import { Route as FarmerEquipmentIndexRouteImport } from './routes/farmer/equipment/index'
import { Route as FarmerEquipmentIdRouteImport } from './routes/farmer/equipment/$id'
import { Route as FarmerRepairIdRouteImport } from './routes/farmer/repair/$id'
import { Route as TechnicianJobIdRouteImport } from './routes/technician/job/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianRoute = TechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerReportBreakdownRoute = FarmerReportBreakdownRouteImport.update({
  id: '/report-breakdown',
  path: '/report-breakdown',
  getParentRoute: () => FarmerRoute,
} as any)
const TechnicianIndexRoute = TechnicianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechnicianRoute,
} as any)
const AdminRepairIdRoute = AdminRepairIdRouteImport.update({
  id: '/repair/$id',
  path: '/repair/$id',
  getParentRoute: () => AdminRoute,
} as any)
const FarmerEquipmentIndexRoute = FarmerEquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerEquipmentIdRoute = FarmerEquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerRepairIdRoute = FarmerRepairIdRouteImport.update({
  id: '/repair/$id',
  path: '/repair/$id',
  getParentRoute: () => FarmerRoute,
} as any)
const TechnicianJobIdRoute = TechnicianJobIdRouteImport.update({
  id: '/job/$id',
  path: '/job/$id',
  getParentRoute: () => TechnicianRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/technician': typeof TechnicianRouteWithChildren
  '/farmer/report-breakdown': typeof FarmerReportBreakdownRoute
  '/admin/': typeof AdminIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/admin/repair/$id': typeof AdminRepairIdRoute
  '/farmer/equipment/$id': typeof FarmerEquipmentIdRoute
  '/farmer/repair/$id': typeof FarmerRepairIdRoute
  '/technician/job/$id': typeof TechnicianJobIdRoute
  '/farmer/equipment/': typeof FarmerEquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/farmer/report-breakdown': typeof FarmerReportBreakdownRoute
  '/admin': typeof AdminIndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/technician': typeof TechnicianIndexRoute
  '/admin/repair/$id': typeof AdminRepairIdRoute
  '/farmer/equipment/$id': typeof FarmerEquipmentIdRoute
  '/farmer/repair/$id': typeof FarmerRepairIdRoute
  '/technician/job/$id': typeof TechnicianJobIdRoute
  '/farmer/equipment': typeof FarmerEquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/technician': typeof TechnicianRouteWithChildren
  '/farmer/report-breakdown': typeof FarmerReportBreakdownRoute
  '/admin/': typeof AdminIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/admin/repair/$id': typeof AdminRepairIdRoute
  '/farmer/equipment/$id': typeof FarmerEquipmentIdRoute
  '/farmer/repair/$id': typeof FarmerRepairIdRoute
  '/technician/job/$id': typeof TechnicianJobIdRoute
  '/farmer/equipment/': typeof FarmerEquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/farmer'
    | '/login'
    | '/technician'
    | '/farmer/report-breakdown'
    | '/admin/'
    | '/farmer/'
    | '/technician/'
    | '/admin/repair/$id'
    | '/farmer/equipment/$id'
    | '/farmer/repair/$id'
    | '/technician/job/$id'
    | '/farmer/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/farmer/report-breakdown'
    | '/admin'
    | '/farmer'
    | '/technician'
    | '/admin/repair/$id'
    | '/farmer/equipment/$id'
    | '/farmer/repair/$id'
    | '/technician/job/$id'
    | '/farmer/equipment'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/farmer'
    | '/login'
    | '/technician'
    | '/farmer/report-breakdown'
    | '/admin/'
    | '/farmer/'
    | '/technician/'
    | '/admin/repair/$id'
    | '/farmer/equipment/$id'
    | '/farmer/repair/$id'
    | '/technician/job/$id'
    | '/farmer/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FarmerRoute: typeof FarmerRouteWithChildren
  LoginRoute: typeof LoginRoute
  TechnicianRoute: typeof TechnicianRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician': {
      id: '/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof TechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/report-breakdown': {
      id: '/farmer/report-breakdown'
      path: '/report-breakdown'
      fullPath: '/farmer/report-breakdown'
      preLoaderRoute: typeof FarmerReportBreakdownRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/technician/': {
      id: '/technician/'
      path: '/'
      fullPath: '/technician/'
      preLoaderRoute: typeof TechnicianIndexRouteImport
      parentRoute: typeof TechnicianRoute
    }
    '/admin/repair/$id': {
      id: '/admin/repair/$id'
      path: '/repair/$id'
      fullPath: '/admin/repair/$id'
      preLoaderRoute: typeof AdminRepairIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/farmer/equipment/': {
      id: '/farmer/equipment/'
      path: '/equipment'
      fullPath: '/farmer/equipment/'
      preLoaderRoute: typeof FarmerEquipmentIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/equipment/$id': {
      id: '/farmer/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/farmer/equipment/$id'
      preLoaderRoute: typeof FarmerEquipmentIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/repair/$id': {
      id: '/farmer/repair/$id'
      path: '/repair/$id'
      fullPath: '/farmer/repair/$id'
      preLoaderRoute: typeof FarmerRepairIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/technician/job/$id': {
      id: '/technician/job/$id'
      path: '/job/$id'
      fullPath: '/technician/job/$id'
      preLoaderRoute: typeof TechnicianJobIdRouteImport
      parentRoute: typeof TechnicianRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRepairIdRoute: typeof AdminRepairIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminRepairIdRoute: AdminRepairIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FarmerRouteChildren {
  FarmerReportBreakdownRoute: typeof FarmerReportBreakdownRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  FarmerEquipmentIdRoute: typeof FarmerEquipmentIdRoute
  FarmerRepairIdRoute: typeof FarmerRepairIdRoute
  FarmerEquipmentIndexRoute: typeof FarmerEquipmentIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerReportBreakdownRoute: FarmerReportBreakdownRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  FarmerEquipmentIdRoute: FarmerEquipmentIdRoute,
  FarmerRepairIdRoute: FarmerRepairIdRoute,
  FarmerEquipmentIndexRoute: FarmerEquipmentIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

interface TechnicianRouteChildren {
  TechnicianIndexRoute: typeof TechnicianIndexRoute
  TechnicianJobIdRoute: typeof TechnicianJobIdRoute
}

const TechnicianRouteChildren: TechnicianRouteChildren = {
  TechnicianIndexRoute: TechnicianIndexRoute,
  TechnicianJobIdRoute: TechnicianJobIdRoute,
}

const TechnicianRouteWithChildren = TechnicianRoute._addFileChildren(
  TechnicianRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FarmerRoute: FarmerRouteWithChildren,
  LoginRoute: LoginRoute,
  TechnicianRoute: TechnicianRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
